[package]
name = "moly"
version = "0.1.0"
authors = ["misabiko"]
edition = "2021"
repository = "https://github.com/misabiko/moly_lang"
default-run = "moly"

[[bin]]
name = "benchmark"

[dependencies]
ctrlc = "3.2.3"
byteorder = "1.4.3"
enum_primitive = "0.1.1"
clap = { version = "3.2.22", features = ["derive"] }
leb128 = "0.2.5"
ieee754 = "0.2.6"
wabt = "0.10.0"