// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Let = 3,
  Identifier = 4,
  String = 5,
  Boolean = 6,
  Return = 9,
  Function = 10
