name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build-test-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: wasm_editor/package-lock.json
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - run: wasm-pack build --target web --out-dir wasm_editor/pkg
      - run: npm ci
        working-directory: wasm_editor
      - run: npm run build
        working-directory: wasm_editor

      - run: cargo test

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: wasm_editor
